# Generated by Django 4.2.30 on 2026-10-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinlipi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinquiry',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='contactinquiry',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='contactinquiry',
            name='plan_interest',
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
